<a href="https://colab.research.google.com/github/JGSukumar/AI-AMRITA/blob/main/Numpy/numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Python Lists in Numpy

In [1]:
myPythonList = [1,9,8,7,3]
print(myPythonList)

[1, 9, 8, 7, 3]


To convert python list to a numpy array by using the object np.array.

In [6]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([1, 9, 8, 7, 3])

assigning variable to array

In [7]:
a  = np.array([1,9,8,7,3])
print(a)

[1 9 8 7 3]


Adding a number to every number in the array

In [8]:
x=numpy_array_from_list + 10
print(x)

[11 19 18 17 13]


To check shape and data type of an array

In [3]:
a  = np.array([1,2,3,4])
print(a.shape)
print(a.dtype)

(4,)
int64


other datatype

In [6]:
b  = np.array([1.1,2.0,3.2,4.4])
print(b.dtype)

float64


2 dimension array

In [7]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


3 dimension array

In [8]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)

(2, 2, 3)


(2, 2, 3)

Numpy Zeros

In [9]:
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [12]:
np.ones((1,2,3), dtype=np.int16)	

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

To reshape data

In [11]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

To flatten data

In [13]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

Horizontal Stack

In [14]:
f = np.array([1,2,3,4])
g = np.array([5,6,7,8])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6 7 8]


Vertical Stack

In [16]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


To generate random numbers

In [17]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.71063057 5.88674392 5.22909554 4.39229904 5.27985009 4.02424152
 4.55748071 4.56736916 5.22496503 5.07566502]


To convert an input to an array asarray()function is used

In [18]:
A = np.matrix(np.ones((4,4)))		
np.array(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


 numpy.arange() is an inbuilt numpy function that returns an ndarray object containing evenly spaced values within a defined interval.

In [3]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

difference between numbers

In [4]:
np.arange(1, 14, 3)

array([ 1,  4,  7, 10, 13])

example for line space

In [6]:
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [7]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as np.linspace.

In [3]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

slicing

In [4]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [5]:
print('First row:', e[0])

print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [6]:
print('Second column:', e[:,1])	

Second column: [2 5]


In [7]:
print(e[1, :2])

[4 5]


To find minimum, maximum, percentile standard deviation and variance, etc from the given elements in the array.

In [8]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.64147324 5.32385225 5.03045266 5.12414152 5.8870773  4.81770902
 5.50314505 4.70137646 5.22816896 4.8209578 ]


To find Minimum

In [9]:
print(np.min(normal_array))

4.641473239010585


To find maximum

In [10]:
print(np.max(normal_array))

5.887077303145483


To find mean

In [11]:
print(np.mean(normal_array))

5.107835425727302


To find median

In [12]:
print(np.median(normal_array))

5.077297089530086


To find Standard deviation

In [13]:
print(np.std(normal_array))

0.37149154751495284


dot product in numpy

In [17]:
a = np.array([1,2])
b = np.array([4,5])
np.dot(a, b)

14

Matrix Multiplication in numpy

In [16]:
a = [[1,2],[3,4]] 
b = [[5,6],[7,8]] 
np.matmul(a, b)

array([[19, 22],
       [43, 50]])

To calculate inverse a matrix using numpy

In [18]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


To Calculate the determinant of a matrix using NumPy?

In [19]:
n_array = np.array([[50, 29], [30, 44]])
  
print("Numpy Matrix is:")
print(n_array)
  
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


Rank of a matrix using numpy

In [20]:
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

np.linalg.matrix_rank(mx)

3

To Calculate Eigenvectors And Eigenvalues With Numpy

In [22]:
example_matrix = np.array([
  [1,2,3,4],
  [5,9,8,7],
  [9,5,1,2],
  [3,4,1,6]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[17.94229064+0.j        -5.21954885+0.j         2.13862911+0.8114655j
  2.13862911-0.8114655j] [[ 0.25300503+0.j          0.37150371+0.j         -0.33805377+0.07152088j
  -0.33805377-0.07152088j]
 [ 0.79568043+0.j          0.41257974+0.j          0.75495106+0.j
   0.75495106-0.j        ]
 [ 0.41225949+0.j         -0.81333189+0.j         -0.02626588+0.21547561j
  -0.02626588-0.21547561j]
 [ 0.36458636+0.j         -0.17393731+0.j         -0.46851477-0.20982751j
  -0.46851477+0.20982751j]]


To Get diagonal of a matrix

In [23]:
gfg = np.matrix('[6, 2; 3, 4]')

diag = gfg.diagonal()
   
print(diag)

[[6 4]]


Matrix transposr

In [24]:
gfg = np.matrix('[4, 1; 12, 3]')

trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


To find trace of a matrix

In [25]:
gfg = np.matrix('[4, 1; 12, 3]')
              
tracem = gfg.trace()
    
print(tracem)

[[7]]
